In [4]:
# importation

import module_stat_desc as msd

liste_salaire = [240000, 350000, 450000, 210000, 560000]
a = msd.statistique_desc(liste_salaire)
print (a)

somme = msd.somme_elt(liste_salaire)
print (somme)

{'min': 210000, 'max': 560000, 'somme': 1810000, 'moyenne': 362000.0}
1810000


# premier pas avec numpy

In [5]:
#Importation de numpy

import numpy as np

liste_age = [23, 20, 31, 25, 26, 29, 22, 27]
tab = np.array(liste_age)
print (tab)

[23 20 31 25 26 29 22 27]


In [6]:
type(tab)

numpy.ndarray

In [15]:
# calculer la moyenne

moyenne = np.mean(tab)
minimum = np.min(tab)
maximum = np.max(tab)
print ("moyenne:", moyenne)
print ("minimum:", minimum)
print ("maximum:", maximum)

# nombre de personne ayant un age superieur a la moyenne

nbre_pers = np.sum(tab > moyenne)
print ("nombre de personne ayant un age superieur a la moyenne:", nbre_pers)

# remplacer ceux qui ont moins de 25 ans par 26
tab[tab <= 25] = 26
print ("Tableau:", tab)

moyenne: 25.375
minimum: 20
maximum: 31
nombre de personne ayant un age superieur a la moyenne: 4
Tableau: [26 26 31 26 26 29 26 27]


In [10]:
moyenne = np.average(tab)
print (moyenne)

25.375


In [22]:
# tableau a deux dimensions

tab = np.array([[5, 12, 18, 4], [9, 8, 15, 2]])
print (tab)
type(tab)

[[ 5 12 18  4]
 [ 9  8 15  2]]


numpy.ndarray

In [24]:
# difference entre liste python et liste numpy
liste_py = [2, 8, 12]
liste_np = np.array([2, 8, 12])
add_py = liste_py + liste_py
add_np = liste_np + liste_np
print (add_py)
print (add_np)

[2, 8, 12, 2, 8, 12]
[ 4 16 24]


In [26]:
# afficher les dimensions du bableau
print (tab.shape)

# acceder a un element du tableau
print (tab[0, 1])
print (tab[1, 3])

(2, 4)
12
2


In [45]:
# calcul

base_np = np.array([25, 29, 36])
hauteur_np = np.array([1.3, 1.5, 1.9])

# calcul avec numpy
v = base_np * hauteur_np
print (v)

# calcul avec liste
base = [25, 29, 36]
hauteur = [1.3, 1.5, 1.9]
v = []
for i in range (len(base)):
    v.append(base[i] * hauteur[i])
print (v)

[32.5 43.5 68.4]
[32.5, 43.5, 68.39999999999999]


# Analyse de donnees financieres

In [47]:
# Exemple 

import numpy as np
np.random.seed(0)
jours = 100

prices_ABC = np.random.normal(100, 0.2, jours)

print (prices_ABC)

[100.35281047 100.08003144 100.1957476  100.44817864 100.3735116
  99.80454442 100.19001768  99.96972856  99.97935623 100.0821197
 100.02880871 100.2908547  100.15220755 100.024335   100.08877265
 100.06673487 100.29881581  99.95896835 100.06261354  99.82918085
  99.48940204 100.13072372 100.17288724  99.851567   100.45395092
  99.70912687 100.0091517   99.96256323 100.30655584 100.29387175
 100.03098949 100.0756325   99.82244285  99.60384071  99.93041757
 100.03126979 100.24605814 100.24047597  99.92253464  99.93953945
  99.79028941  99.71599641  99.65874596 100.39015508  99.89806956
  99.91238514  99.74944093 100.15549807  99.67722043  99.95745194
  99.82090669 100.0773805   99.89783897  99.76387356  99.99436355
 100.08566637 100.01330344 100.06049438  99.87313558  99.92745177
  99.86550791  99.92808937  99.83737074  99.65474348 100.03548523
  99.91964381  99.67396033 100.09255645  99.81854033 100.01038908
 100.14581811 100.02579658 100.22788014  99.75303484 100.08046833
  99.8630379

In [53]:
# Generer des donnees

import numpy as np
jours = 100
donnees_ABC= np.random.normal(500, 25, jours)
donnees_XYZ= np.random.normal(600, 26, jours)
donnees_123= np.random.normal(700, 27, jours)
print  ("Prix de cloture ABC", donnees_ABC)
print  ("Prix de cloture XYZ", donnees_XYZ)
print  ("Prix de cloture 123", donnees_123)

Prix de cloture ABC [461.23926637 510.43297053 476.39078773 505.9525787  464.85092709
 485.24855885 497.23776487 458.4825047  502.87869683 490.52131093
 456.44109505 467.41893115 515.1280021  522.38889964 496.70228401
 510.1190453  505.59608908 508.24057455 532.14960018 462.32504004
 516.91151831 490.44977611 494.39352664 492.44375674 490.62132208
 469.34509521 504.58347998 541.77357582 498.59667449 499.96537393
 482.81752407 497.06313634 511.65416065 490.74393898 488.65489897
 510.0816135  477.04988075 506.31241568 520.50804493 533.99871354
 497.74044982 534.189931   525.86024716 475.09468399 469.55153721
 492.37590905 525.72338731 498.19282481 484.98356106 538.8060795
 507.1726122  441.98514311 507.92901566 513.00101536 505.64021636
 511.24280251 498.31810978 467.04010326 490.73239992 476.35960511
 476.68147723 468.42329127 511.31222732 502.44740364 488.79586593
 483.76655181 499.41442237 526.9798682  449.89460711 509.42191302
 486.35720065 452.88535388 451.35742292 477.18041265 505.

In [60]:
# Calcul des statistiques descriptives

print ("Le resultats des calculs statistiques pour l'entreprise ABC sont:")
Moyenne = np.mean(donnees_ABC)
Ecart_type = np.std(donnees_ABC)
minimum = np.min(donnees_ABC)
maximum = np.max(donnees_ABC)
print ("Moyenne:", Moyenne)
print ("Ecart_type:", Ecart_type)
print ("Minimum:", minimum)
print ("Maximum:", maximum)

print ("Le resultats des calculs statistiques pour l'entreprise XYZ sont:")
Moyenne = np.mean(donnees_XYZ)
Ecart_type = np.std(donnees_XYZ)
minimum = np.min(donnees_XYZ)
maximum = np.max(donnees_XYZ)
print ("Moyenne:", Moyenne)
print ("Ecart_type:", Ecart_type)
print ("Minimum:", minimum)
print ("Maximum:", maximum)

print ("Le resultats des calculs statistiques pour l'entreprise 123 sont:")
Moyenne = np.mean(donnees_123)
Ecart_type = np.std(donnees_123)
minimum = np.min(donnees_123)
maximum = np.max(donnees_123)
print ("Moyenne:", Moyenne)
print ("Ecart_type:", Ecart_type)
print ("Minimum:", minimum)
print ("Maximum:", maximum)

Le resultats des calculs statistiques pour l'entreprise ABC sont:
Moyenne: 496.6262592459129
Ecart_type: 25.075324107846008
Minimum: 429.13613736813244
Maximum: 559.5186337804937
Le resultats des calculs statistiques pour l'entreprise XYZ sont:
Moyenne: 596.7864186284069
Ecart_type: 24.4826114949019
Minimum: 541.6216371423435
Maximum: 664.9272101812621
Le resultats des calculs statistiques pour l'entreprise 123 sont:
Moyenne: 699.2386234426045
Ecart_type: 25.109111339295886
Minimum: 630.2644909098115
Maximum: 770.0494638697401


In [77]:
# Remplir tout un tableau avec la valeur 0
b = np.zeros(5)
print (b)

# Remplir tout un tableau avec la valeur 4
c = np.ones(4)
print (c)

# Remplir tout un tableau dont les valeurs vont de 1 a 9
a = np.arange(8)
print(a)

# Trier mon tableau
T = np.array([8, 2, 1, 9, 3, 5, 4, 7, 6])
tab = np.sort(T)
print (tab)

# concatener deux tableau
tab1 = np.array([1, 2, 3, 4])
tab2 = np.array([5, 6, 7, 8])
tb = np.concatenate((tab1, tab2))
print (tb)

# remodeler le tableau en plusieurs lignes et colonnes
tb = tb.reshape(4, 2)
print (tb)

# remplir un tableau de 1 a 24 qui tient sur 2 lignes et 12 colonnes
tabl = np.arange(1, 25).reshape(2, 12)
print(tabl)

# Divisez un tableau
d = np.hsplit(tabl, 4)
print (d)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [16, 17, 18]]), array([[ 7,  8,  9],
       [19, 20, 21]]), array([[10, 11, 12],
       [22, 23, 24]])]


In [82]:
# On aura a la fin la somme des lignes sum(axis = 0) et la somme des colonnes sum(axis = 1)

b = np.array([[1, 1], [2, 2]])
print (b)
print (b.sum(axis = 0))
print (b.sum(axis = 1))

[[1 1]
 [2 2]]
[3 3]
[2 4]


In [83]:
# recuperer les elements du tableau sans doublon

a = np.array([12, 15, 11, 11, 12, 14, 16, 18, 16, 20, 20, 13, 11, 12, 14])
b = np.unique(a)
print (b)

[11 12 13 14 15 16 18 20]


In [84]:
print(tabl)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [87]:
# Transposer le tableau

Tr = np.transpose(tabl)
print (Tr)

[[ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]
 [12 24]]


In [88]:
print (b)

[11 12 13 14 15 16 18 20]


In [92]:
# Inverser mon tableau

I = np.flip(b)
print (I)


[20 18 16 15 14 13 12 11]
[[24 23 22 21 20 19 18 17 16 15 14 13]
 [12 11 10  9  8  7  6  5  4  3  2  1]]


In [98]:
# Inverser le tableau tabl
print ("tableau tabl inverse")
i = np.flip(tabl)
print (i)

# Inverser uniquement les lignes
print ("tableau tabl avec les lignes inverses")
i = np.flipud(tabl) # i = np.flip(tabl, axis = 0)
print (i)

# Inverser uniquement les colonnes
print ("tableau tabl avec les colonnes inverses")
i = np.fliplr(tabl) # i = np.flip(tabl, axis = 1)
print (i)



tableau tabl inverse
[[24 23 22 21 20 19 18 17 16 15 14 13]
 [12 11 10  9  8  7  6  5  4  3  2  1]]
tableau tabl avec les lignes inverses
[[13 14 15 16 17 18 19 20 21 22 23 24]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]]
tableau tabl avec les colonnes inverses
[[12 11 10  9  8  7  6  5  4  3  2  1]
 [24 23 22 21 20 19 18 17 16 15 14 13]]


In [99]:
o = np.roll(tabl, -2)
print (o)

[[ 3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24  1  2]]
